//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.openlr.org/openlr")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.openlr.org/openlr", IsNullable=false)]
public partial class OpenLR {
    
    private string locationIDField;
    
    private XMLLocationReference xMLLocationReferenceField;
    
    private BinaryLocationReference[] binaryLocationReferencesField;
    
    private AdditionalInformation additionalInformationField;
    
    /// <remarks/>
    public string LocationID {
        get {
            return this.locationIDField;
        }
        set {
            this.locationIDField = value;
        }
    }
    
    /// <remarks/>
    public XMLLocationReference XMLLocationReference {
        get {
            return this.xMLLocationReferenceField;
        }
        set {
            this.xMLLocationReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public BinaryLocationReference[] BinaryLocationReferences {
        get {
            return this.binaryLocationReferencesField;
        }
        set {
            this.binaryLocationReferencesField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalInformation AdditionalInformation {
        get {
            return this.additionalInformationField;
        }
        set {
            this.additionalInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class XMLLocationReference {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AreaLocationReference", typeof(AreaLocationReference))]
    [System.Xml.Serialization.XmlElementAttribute("LineLocationReference", typeof(LineLocationReference))]
    [System.Xml.Serialization.XmlElementAttribute("PointLocationReference", typeof(PointLocationReference))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class AreaLocationReference {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CircleLocationReference", typeof(CircleLocationReference))]
    [System.Xml.Serialization.XmlElementAttribute("ClosedLineLocationReference", typeof(ClosedLineLocationReference))]
    [System.Xml.Serialization.XmlElementAttribute("GridLocationReference", typeof(GridLocationReference))]
    [System.Xml.Serialization.XmlElementAttribute("PolygonLocationReference", typeof(PolygonLocationReference))]
    [System.Xml.Serialization.XmlElementAttribute("RectangleLocationReference", typeof(RectangleLocationReference))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class CircleLocationReference {
    
    private GeoCoordinate geoCoordinateField;
    
    private string radiusField;
    
    /// <remarks/>
    public GeoCoordinate GeoCoordinate {
        get {
            return this.geoCoordinateField;
        }
        set {
            this.geoCoordinateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class GeoCoordinate {
    
    private Coordinates coordinatesField;
    
    /// <remarks/>
    public Coordinates Coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class Coordinates {
    
    private double longitudeField;
    
    private double latitudeField;
    
    /// <remarks/>
    public double Longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    public double Latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class AdditionalData {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class LocationName {
    
    private string nameField;
    
    private string roadnameField;
    
    private string fromAreaField;
    
    private string toAreaField;
    
    private string startField;
    
    private string endField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Roadname {
        get {
            return this.roadnameField;
        }
        set {
            this.roadnameField = value;
        }
    }
    
    /// <remarks/>
    public string FromArea {
        get {
            return this.fromAreaField;
        }
        set {
            this.fromAreaField = value;
        }
    }
    
    /// <remarks/>
    public string ToArea {
        get {
            return this.toAreaField;
        }
        set {
            this.toAreaField = value;
        }
    }
    
    /// <remarks/>
    public string Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public string End {
        get {
            return this.endField;
        }
        set {
            this.endField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class AdditionalInformation {
    
    private Rectangle boundingBoxField;
    
    private string mapDatabaseField;
    
    private LocationName locationNameField;
    
    private AdditionalData additionalDataField;
    
    /// <remarks/>
    public Rectangle BoundingBox {
        get {
            return this.boundingBoxField;
        }
        set {
            this.boundingBoxField = value;
        }
    }
    
    /// <remarks/>
    public string MapDatabase {
        get {
            return this.mapDatabaseField;
        }
        set {
            this.mapDatabaseField = value;
        }
    }
    
    /// <remarks/>
    public LocationName LocationName {
        get {
            return this.locationNameField;
        }
        set {
            this.locationNameField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalData AdditionalData {
        get {
            return this.additionalDataField;
        }
        set {
            this.additionalDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class Rectangle {
    
    private Coordinates lowerLeftField;
    
    private Coordinates upperRightField;
    
    /// <remarks/>
    public Coordinates LowerLeft {
        get {
            return this.lowerLeftField;
        }
        set {
            this.lowerLeftField = value;
        }
    }
    
    /// <remarks/>
    public Coordinates UpperRight {
        get {
            return this.upperRightField;
        }
        set {
            this.upperRightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class BinaryLocationReference {
    
    private string idField;
    
    private string versionField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class ClosedLineLocationReference {
    
    private LocationReferencePoint[] locationReferencePointField;
    
    private LineAttributes lastLineField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationReferencePoint")]
    public LocationReferencePoint[] LocationReferencePoint {
        get {
            return this.locationReferencePointField;
        }
        set {
            this.locationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public LineAttributes LastLine {
        get {
            return this.lastLineField;
        }
        set {
            this.lastLineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class LocationReferencePoint {
    
    private Coordinates coordinatesField;
    
    private LineAttributes lineAttributesField;
    
    private PathAttributes pathAttributesField;
    
    /// <remarks/>
    public Coordinates Coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    public LineAttributes LineAttributes {
        get {
            return this.lineAttributesField;
        }
        set {
            this.lineAttributesField = value;
        }
    }
    
    /// <remarks/>
    public PathAttributes PathAttributes {
        get {
            return this.pathAttributesField;
        }
        set {
            this.pathAttributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class LineAttributes {
    
    private FRC_Type fRCField;
    
    private FOW_Type fOWField;
    
    private string bEARField;
    
    /// <remarks/>
    public FRC_Type FRC {
        get {
            return this.fRCField;
        }
        set {
            this.fRCField = value;
        }
    }
    
    /// <remarks/>
    public FOW_Type FOW {
        get {
            return this.fOWField;
        }
        set {
            this.fOWField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string BEAR {
        get {
            return this.bEARField;
        }
        set {
            this.bEARField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public enum FRC_Type {
    
    /// <remarks/>
    FRC0,
    
    /// <remarks/>
    FRC1,
    
    /// <remarks/>
    FRC2,
    
    /// <remarks/>
    FRC3,
    
    /// <remarks/>
    FRC4,
    
    /// <remarks/>
    FRC5,
    
    /// <remarks/>
    FRC6,
    
    /// <remarks/>
    FRC7,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public enum FOW_Type {
    
    /// <remarks/>
    UNDEFINED,
    
    /// <remarks/>
    MOTORWAY,
    
    /// <remarks/>
    MULTIPLE_CARRIAGEWAY,
    
    /// <remarks/>
    SINGLE_CARRIAGEWAY,
    
    /// <remarks/>
    ROUNDABOUT,
    
    /// <remarks/>
    TRAFFICSQUARE,
    
    /// <remarks/>
    SLIPROAD,
    
    /// <remarks/>
    OTHER,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class PathAttributes {
    
    private FRC_Type lFRCNPField;
    
    private string dNPField;
    
    /// <remarks/>
    public FRC_Type LFRCNP {
        get {
            return this.lFRCNPField;
        }
        set {
            this.lFRCNPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string DNP {
        get {
            return this.dNPField;
        }
        set {
            this.dNPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class GridLocationReference {
    
    private Rectangle rectangleField;
    
    private short numColumnsField;
    
    private short numRowsField;
    
    /// <remarks/>
    public Rectangle Rectangle {
        get {
            return this.rectangleField;
        }
        set {
            this.rectangleField = value;
        }
    }
    
    /// <remarks/>
    public short NumColumns {
        get {
            return this.numColumnsField;
        }
        set {
            this.numColumnsField = value;
        }
    }
    
    /// <remarks/>
    public short NumRows {
        get {
            return this.numRowsField;
        }
        set {
            this.numRowsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class RectangleLocationReference {
    
    private Rectangle rectangleField;
    
    /// <remarks/>
    public Rectangle Rectangle {
        get {
            return this.rectangleField;
        }
        set {
            this.rectangleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class PolygonLocationReference {
    
    private Coordinates[] polygonCornersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Coordinates[] PolygonCorners {
        get {
            return this.polygonCornersField;
        }
        set {
            this.polygonCornersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class PoiWithAccessPoint {
    
    private LocationReferencePoint locationReferencePointField;
    
    private LastLocationReferencePoint lastLocationReferencePointField;
    
    private Offsets offsetsField;
    
    private Coordinates coordinatesField;
    
    private SideOfRoad_Type sideOfRoadField;
    
    private Orientation_Type orientationField;
    
    public PoiWithAccessPoint() {
        this.sideOfRoadField = SideOfRoad_Type.ON_ROAD_OR_UNKNOWN;
        this.orientationField = Orientation_Type.NO_ORIENTATION_OR_UNKNOWN;
    }
    
    /// <remarks/>
    public LocationReferencePoint LocationReferencePoint {
        get {
            return this.locationReferencePointField;
        }
        set {
            this.locationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public LastLocationReferencePoint LastLocationReferencePoint {
        get {
            return this.lastLocationReferencePointField;
        }
        set {
            this.lastLocationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public Offsets Offsets {
        get {
            return this.offsetsField;
        }
        set {
            this.offsetsField = value;
        }
    }
    
    /// <remarks/>
    public Coordinates Coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(SideOfRoad_Type.ON_ROAD_OR_UNKNOWN)]
    public SideOfRoad_Type SideOfRoad {
        get {
            return this.sideOfRoadField;
        }
        set {
            this.sideOfRoadField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(Orientation_Type.NO_ORIENTATION_OR_UNKNOWN)]
    public Orientation_Type Orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class LastLocationReferencePoint {
    
    private Coordinates coordinatesField;
    
    private LineAttributes lineAttributesField;
    
    /// <remarks/>
    public Coordinates Coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    public LineAttributes LineAttributes {
        get {
            return this.lineAttributesField;
        }
        set {
            this.lineAttributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class Offsets {
    
    private string posOffField;
    
    private string negOffField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PosOff {
        get {
            return this.posOffField;
        }
        set {
            this.posOffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NegOff {
        get {
            return this.negOffField;
        }
        set {
            this.negOffField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public enum SideOfRoad_Type {
    
    /// <remarks/>
    ON_ROAD_OR_UNKNOWN,
    
    /// <remarks/>
    RIGHT,
    
    /// <remarks/>
    LEFT,
    
    /// <remarks/>
    BOTH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public enum Orientation_Type {
    
    /// <remarks/>
    NO_ORIENTATION_OR_UNKNOWN,
    
    /// <remarks/>
    WITH_LINE_DIRECTION,
    
    /// <remarks/>
    AGAINST_LINE_DIRECTION,
    
    /// <remarks/>
    BOTH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class PointAlongLine {
    
    private LocationReferencePoint locationReferencePointField;
    
    private LastLocationReferencePoint lastLocationReferencePointField;
    
    private Offsets offsetsField;
    
    private SideOfRoad_Type sideOfRoadField;
    
    private Orientation_Type orientationField;
    
    public PointAlongLine() {
        this.sideOfRoadField = SideOfRoad_Type.ON_ROAD_OR_UNKNOWN;
        this.orientationField = Orientation_Type.NO_ORIENTATION_OR_UNKNOWN;
    }
    
    /// <remarks/>
    public LocationReferencePoint LocationReferencePoint {
        get {
            return this.locationReferencePointField;
        }
        set {
            this.locationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public LastLocationReferencePoint LastLocationReferencePoint {
        get {
            return this.lastLocationReferencePointField;
        }
        set {
            this.lastLocationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public Offsets Offsets {
        get {
            return this.offsetsField;
        }
        set {
            this.offsetsField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(SideOfRoad_Type.ON_ROAD_OR_UNKNOWN)]
    public SideOfRoad_Type SideOfRoad {
        get {
            return this.sideOfRoadField;
        }
        set {
            this.sideOfRoadField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(Orientation_Type.NO_ORIENTATION_OR_UNKNOWN)]
    public Orientation_Type Orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class PointLocationReference {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GeoCoordinate", typeof(GeoCoordinate))]
    [System.Xml.Serialization.XmlElementAttribute("PoiWithAccessPoint", typeof(PoiWithAccessPoint))]
    [System.Xml.Serialization.XmlElementAttribute("PointAlongLine", typeof(PointAlongLine))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.openlr.org/openlr")]
public partial class LineLocationReference {
    
    private LocationReferencePoint[] locationReferencePointField;
    
    private LastLocationReferencePoint lastLocationReferencePointField;
    
    private Offsets offsetsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LocationReferencePoint")]
    public LocationReferencePoint[] LocationReferencePoint {
        get {
            return this.locationReferencePointField;
        }
        set {
            this.locationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public LastLocationReferencePoint LastLocationReferencePoint {
        get {
            return this.lastLocationReferencePointField;
        }
        set {
            this.lastLocationReferencePointField = value;
        }
    }
    
    /// <remarks/>
    public Offsets Offsets {
        get {
            return this.offsetsField;
        }
        set {
            this.offsetsField = value;
        }
    }
}
