name: .NET Core

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core 6.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore packages.
      run: dotnet restore
    - name: Build all projects.
      run: dotnet build --configuration Release --no-restore

    - name: Unittests.
      run: dotnet test
      working-directory: ./test/OpenLR.Test/

    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/OpenLR/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/OpenLR.Geo/

    - name: Nuget push Github
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/itinero/index.json
      working-directory: ./src/
      
    - name: Nuget push
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
      working-directory: ./src/